src/app/containers/FastBtcForm/index.tsx
The problem wasn't in the QR resolution, size, or encoding. The problem was with the color. Had to revert the colors and add a margin.
=> Fix QRCode readability

package.json
The buddy pipeline checks failed with the previous PR because the bundle size was too large. I think this might be because I had node-sass installed as a dependency instead of a devDependency - I've change that so hopefully it will be fixed
=> Changed node-sass to dev dependency

src/app/components/LanguageToggle/index.tsx, src/styles/sass/new-design.scss
Updates html lang attribute when updating language in the footer so that the styling can know whether it should style a little bit differently based on the language it is in.  It makes the font size a little bit smaller so that the tabs fit in one row since there is more text for that language.
=> Fixes #92 lend/borrow tabs for pt_br on mobile screen

src/app/components/MetaMaskDiscouragementNotifyModal/index.tsx, src/app/components/NotificationForm/NotificationFormComponent/index.tsx, src/app/components/NotificationForm/NotificationFormContainer/index.tsx, src/app/containers/ActiveUserLoans/index.tsx, src/app/containers/BorrowHistory/index.tsx, src/app/containers/WalletPage/index.tsx, src/locales/en/translation.json, src/locales/es/translation.json, src/locales/pt_br/translation.json
Added strings for all text that is referenced in #143, with the exception of this one (as I believe this is just a temporary warning):
https://github.com/DistributedCollective/Sovryn-frontend/issues/143#issuecomment-766356682
All of these will need appropriate translations, I have just copied over the english text.
There is one string that I spotted in NotificationFormContainer::86 that looks like it needs translation, but I'm not sure how you would like to handle this one as there are some newline characters and piping that probably shouldn't go into the translation json:
`${timestamp} \n \n Please confirm that the details associated with this account will now be: \n \n Username: ${name} \n Email: ${email}`
I also reviewed the rest of the Components/Containers in the app and have found a …
=> Add translation strings for #143

src/app/components/ActiveUserLoanContainer/components/ActiveLoanTableDesktop/index.tsx, src/app/components/AssetWalletBalance/index.tsx, src/app/containers/LiquidityAddContainer/ExpectedPoolTokens.tsx, src/app/containers/LiquidityRemoveContainer/index.tsx, src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
I've updated these to consistently use `weiTo18()` formatting instead of wei's
=> Update asset value tooltip precision for #344

src/app/containers/EngageWalletDialog/component/screen2/index.tsx, src/app/containers/EngageWalletDialog/component/screen4/index.tsx, src/utils/classifiers.ts
The engage wallet tutorial shows Mainnet settings, even when on Testnet - I've updated this so it pulls through the relevant values depending on which network is currently in use
=> Add testnet settings to EngageWalletDialog setup tutorial

src/app/containers/EngageWalletDialog/component/screen2/index.tsx, src/app/containers/EngageWalletDialog/component/screen4/index.tsx, src/utils/classifiers.ts
The team mentioned in Discord that the RPC node URLs on the Gitbook docs aren't up to date, so I've modified my recent change from 99c0d30 to use the correct URLs (and removed the duplicate node definitions I mistakenly added last time)
=> Update rpcNode urls (and removed duplicate node defs)

src/app/containers/StatsPage/components/TVL.tsx, src/app/containers/StatsPage/components/TradingVolume.tsx, src/app/containers/StatsPage/index.tsx, src/app/containers/StatsPage/types.ts
This is two new components for the "Stats" page of the dapp, showing Trading Volume and TVL,. It looks like this:
=> Changed stats page to include tvl and trading volume

src/app/components/WhitelistedNotification/index.tsx, src/locales/en/translation.json, src/locales/es/translation.json, src/locales/pt_br/translation.json
=> New copy for whitelist notification

src/app/components/Footer/index.tsx
Make the link for the opt-out also work for non-Chromium-base browsers
=> Improve opt-out link

src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx, src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx, src/locales/en/translation.json
Reverts incorrectly applied label update for asset selector in pool dialogs (v2 pools), on Liquidity Mining page
=> [Liquidity-Mining] Revert incorrect Asset label

src/locales/en/translation.json
I think when the user didn't provided liquidity, the message should be to encourage adding liquidity.
=> Minor change on EN

src/app/components/TradingChart/index.tsx, src/app/components/TradingChart/storage.ts, src/app/components/TradingChart/streaming.ts, src/utils/classifiers.ts
Implemented with localStorage for storing user drawings, which allows for around 5-10 sets of saved drawings/indicators per user.
If we find this does not offer enough storage we can investigate the full solution, but it requires a database and REST api to be setup.
=> [Trading Chart] Store user drawings/indicators

src/app/components/TradingChart/index.tsx
Increase number of indicators that can be added concurrently to the Trading Chart by a user, to 15
=> [Trading Chart] Increase indicator limit

src/app/components/LocalSharedArrayBuffer/index.tsx, src/app/pages/LiquidityMining/index.tsx
that enables liquidity mining charts to load on localhost when using mainnet.
See https://stackoverflow.com/a/67587272 for a description of the problem and a simple solution that does not involve upgrading React.
Also see https://github.com/facebook/react/issues/20829#issuecomment-802088260
=> Adds a hidden LocalSharedArrayBuffer component

src/app/components/UserAssets/FishDollarValue.tsx, src/app/components/UserAssets/index.tsx, src/utils/dictionaries/assets-dictionary.ts
Currently errors will be thrown when accessing Portfolio page with wallet engaged, when testing `development` branch on mainnet. This is due to the Fish token contract not being deployed on mainnet yet. This PR hides it from asset list in `src\utils\dictionaries\assets-dictionary.ts` and fixes an error due to a failed contract call via `useGetFishDollarValue()` hook. Simply removing the Fish asset from asset dictionary will not work as the `useGetFishDollarValue` hook is executed in `src\app\components\UserAssets\index.tsx` for all assets.
@creed-victor can you check if my solution (refactoring hook call into a custom component for Fish asset) could be implemented in a more elegant way?
Sample error:
=> [Portfolio] Fix Fish token mainnet issues

src/locales/en/translation.json
=> Fix string in EN

src/app/pages/LendingPage/index.tsx, src/app/pages/LiquidityMining/index.tsx, src/utils/dateHelpers.ts
Updates recalibration date to August 23rd for Loot Drop promos (Lend and Yield Farm pages), and automates future changes to avoid us having to manually update them each Monday.
=> Automatically update recalibration dates

src/styles/tailwindcss/base.css
Resolves https://taiga.sovryn.app/project/sovryn-light/issue/424
Added * to prevent auto removal on CSS cleanup on production build
=> [Styling] remove :focus outline

src/app/containers/SwapFormContainer/index.tsx, src/app/pages/LandingPage/index.tsx, src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
Reverts DistributedCollective/Sovryn-frontend#1755
Token is now enabled in smart-contracts and hotfix can be safely rollbacked to use swap external contract.
=> Revert "hotfix: use wrbtc wrapper proxy for bnbs swaps"

src/utils/blockchain/contracts.testnet.ts
Changed addresses of SOV/RBTC, XUSD/RBTC, FISH/RBTC, BNBS/RBTC, ETHS/RBTC & MOC/RBTC AMM pool converter addresses.
QA:
- deposit to AMM pools (Yield Farm)
- withdraw from AMM pools
- make swaps using these pools
- open trade positions
- add margin to position
- close position
=> changed testnet amm converter addresses

src/app/hooks/lending/useLending_burn.ts, src/app/hooks/lending/useLending_mint.ts, src/utils/classifiers.ts
Currently HW wallet users are experiencing gas limit issues when withdrawing assets from Lend pools. This PR bumps the gas limit and forces the limit to be respected when creating the tx.
=> fix: bump gas limit for unlend, ensure lend/unlend respects gas limits

package.json, yarn.lock
This PR updates `@sovyn/react-wallet` which allows users to use ethereum derivation paths when connecting their ledger or trezor wallets. 
QA:
- open dapp, click "connect wallet", select "hardware" and then "ledger" in dialog
- choose "ethereum - xxxxx" derivation path from the list
- connect wallet
- make swaps, trades, etc to confirm transactions can be submitted
- repeat with trezor
Note: when using etheureum HD derivation path with ledger,  make sure to have Ethereum app opened in ledger device (instead of rsk app)
=> allow ethereum HD derivation paths

src/app/pages/BridgeDepositPage/saga.ts
Resets USDT allowance to 0 before requesting approval for more (ethereum side)
QA:
- Open portfolio
- Select XUSD -> Deposit
- Choose USDT as deposit token
- Enter amount you want to deposit (do not use entire balance)
- Confirm transaction for approval tx
- Cancel second transaction (the deposit one)
- Repeat it for second time but do not cancel transaction anymore and with higher amount than first time: you should be asked to confirm 3 transactions (2 approval, 1 deposit)
- Repeat it for third time: you should be asked to confirm 2 transactions (1 approval, 1 deposit)
Try same thing for any other token than USDT too - you should be asked to confirm 2 transactions and not 3 for other ones.
=> fix(bridge): reset USDT allowance to 0

src/app/components/UserAssets/index.tsx
Simple change to switch position of Buy and Deposit buttons for RBTC asset on Portfolio page:
https://discord.com/channels/729675474665603133/750376232771780608/938565395219087371
ACs:
- Ensure that the buttons on Portfolio page for RBTC are in following order: "Buy", "Deposit", "Withdraw"
=> fix: switch placement of 'buy' & 'deposit' buttons

package.json, src/app/containers/WalletProvider/index.tsx, yarn.lock
https://sovryn.monday.com/boards/2218344956/pulses/2243609008
Hides unsupported wallets for chain.
QA in perpetuals page, click connect wallet and verify that "Mobile" (Wallet Connect) and "Portis" in Browser screen is missing.
In homepage, click connect wallet and verify that "Mobile" and "Portis" are there.
=> fix: hide unsupported wallets

public/charting_library_custom.css, src/app/pages/PerpetualPage/PerpetualPageContainer.tsx, src/app/pages/PerpetualPage/components/TradingChart/datafeed.ts, src/app/pages/PerpetualPage/components/TradingChart/helpers.ts, src/app/pages/PerpetualPage/components/TradingChart/index.tsx, src/app/pages/PerpetualPage/components/TradingChart/storage.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2350572876
Also fixed the used colors, changed the background to #222222, because of upcoming changes.
Added 5min candles and changed the default timezone to UTC same as Recent Trades
=> [Perpetuals] add TradingChart custom colors, UTC timezone and 5min candles

src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
We changed the backend a bit so that the text to login to backend is [ ANY MESSAGE ]: [ DATE ]
This is so we can reuse this logic and make the text as specific/descriptive as we want and as long as the date is within a minute of now, the authentication should pass
=> Add a : in the backend login text

src/app/components/Header/index.tsx, src/app/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2399662369
Removed Perpetuals from router and navigation.
@creed-victor I did not make any changes to FastBTC so navigating to /fast-btc/withdraw/bsc still allows for btc to bsc transfers and links to perps. Though there is no link to this path in the dapp. Do you think that could cause problems or can we leave it in in the meantime?
=> [Perpetuals] disable perpetuals on mainnet

src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx, src/app/pages/PerpetualPage/components/ClosePositionDialog/components/SlippageFormStep.tsx, src/app/pages/PerpetualPage/components/ClosePositionDialog/components/TradeFormStep.tsx, src/app/pages/PerpetualPage/components/ContractDetails/index.tsx, src/app/pages/PerpetualPage/components/EditLeverageDialog/index.tsx, src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx, src/app/pages/PerpetualPage/components/EditPositionSizeDialog/components/SlippageFormStep.tsx, src/app/pages/PerpetualPage/components/EditPositionSizeDialog/components/TradeFormStep.tsx, src/app/pages/PerpetualPage/components/NewPositionCard/components/SlippageFormStep.tsx, src/app/pages/PerpetualPage/components/PairSelector/PairSelectorButton.tsx, src/app/pages/PerpetualPage/components/RecentTradesTable/index.tsx, src/app/pages/PerpetualPage/components/TradeDetails/index.tsx, src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx, src/app/pages/PerpetualPage/components/TradeDialog/index.tsx, src/app/pages/PerpetualPage/components/TradeForm/index.tsx, src/app/pages/PerpetualPage/contexts/PerpetualQueriesContext.tsx, src/app/pages/PerpetualPage/contexts/RecentTradesContext.tsx, src/app/pages/PerpetualPage/hooks/usePerpetual_AmmDepthChart.ts, src/app/pages/PerpetualPage/hooks/usePerpetual_ClosedPositions.ts, src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts, src/app/pages/PerpetualPage/hooks/usePerpetual_OpenPositions.ts, src/app/pages/PerpetualPage/hooks/usePerpetual_accountBalance.ts, src/app/pages/PerpetualPage/hooks/usePerpetual_getCurrentPairId.ts, src/app/pages/PerpetualPage/hooks/usePerpetual_openTrade.ts
Partially resolves https://sovryn.monday.com/boards/2218344956/pulses/2508572752 .
This PR changes the way we fetch data (ammState, traderState, ...) in perpetuals. Historically, we fetched them for the current pair only but we need to fetch them for all the pairs at once so we can display all of the Open positions, different Mark prices etc.
=> Fetch data for all the pairs

package.json, yarn.lock
removes errors when building production build
@ShynRou, as I understood lib was updated as per your request, as it's major version changed - there is something that can break some functionality in the FE?
if so, will use this branch as staging deployment for margin trading testing on mainnet
=> fix: bump perpetuals lib version

src/app/pages/BuySovPage/components/BuyForm/useSlippage.ts, src/app/pages/MarginTradePage/components/TradeDialog/TradeDialogContent.tsx, src/app/pages/MarginTradePage/components/TradeDialog/index.tsx, src/app/pages/MarginTradePage/components/TradeForm/index.tsx
temporary quick fixes:
- fixes estimated liquidation price in dialog
- hides incorrect estimated entry price in margin form
- hides incorrect estimated liquidation price in margin form
- enforces `minReturn` (slippage) to 1 for SOV/RBTC pair
=> fix: margin trading issues

src/app/components/Checkbox/index.module.scss, src/app/components/FirstVisitDisclaimerDialog/index.tsx, src/app/components/MobileBrowsersWarningDialog/index.tsx, src/app/components/OptOutDialog/index.tsx, src/app/pages/MarginTradePage/components/TradeDialog/TradeDialogContent.tsx, src/app/pages/OriginsLaunchpad/pages/SalesDay/pages/ImportantInformationStep/index.tsx, src/styles/sass/blueprint-override.scss
https://sovryn.monday.com/boards/2218344956/pulses/2426081428
Checkbox'es changed at:
- First visit / welcome dialog (use incognito to open)
- Mobile browser warning dialog (use mobile device)
- Tracking opt out dialog (click "Opt-out from Google Analytics" in the footer)
- Margin Trade dialog - failed tx simulation error bypass (only visible when simulator expects transaction to fail)
- Origins Sale -> Terms & Conditions to accept before sale (only visible when sale is active)
Old checkboxes has check mark symbol which is white, new ones - black.
=> feat: enforce new checkboxs

package.json, yarn.lock
Added newest sovryn wallet library which introduces deprecation message for nifty wallet.
AC:
- When connecting to the dapp, Nifty Wallet has deprecation message with hyperlink linking to the wiki
=> chore(deps): bump sovryn wallet version

public/index.html
https://sovryn.monday.com/boards/2218344956/pulses/2775984700
Adds support for Sovryn favicon to appear in list of Connected Sites in Metamask
=> feat: add extra rel attribute to favicon for metamask "connected sites"

src/utils/graphql/rsk/generated.tsx, src/utils/graphql/rsk/operations/getSwapHistory.graphql
Changes to the subgraph mean that limit orders were showing up in User Swap/Spot history.
This PR adds a where clause isLimit: false to the graphql query to fix this
Jira ticket: https://sovryn.atlassian.net/browse/SOV-716
=> Added isLimit where clause to swap history

src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
Fixes an issue found by Julio on Margin trade page - the page was crashing because returned error was an object instead of a string.
=> Fix ErrorBadge fail in MarginTrade

src/app/containers/WalletProvider/saga.ts
Resolves issue where analytics tracking endpoint throws error when you don't send cid (GA id) - e.g. if you use browser that blocks it, or don't have tracking cookie enabled. This PR changes query so it only adds that prop to payload if it exists
=> chore: fix analytics visit tracking with no GA id

src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
Reverted breaking changes from this commit: https://github.com/DistributedCollective/Sovryn-frontend/commit/c3321f11d75a323d671fd080aae52d6be4a4de17
New users can now sign up for notifications.
There is still a bug where the notification sign-up only works on the margin trade page (this is a separate bug)
Resolves https://sovryn.atlassian.net/browse/SOV-970
=> Fix/notification auth failing/sov 970

src/app/components/PairNavbar/utils.ts, src/app/components/PairNavbarInfo/index.tsx
Hotfix for the issue where the pair navbar dropdown menu shows the wrong 24h % change. 
Also fix for another issue I spotted where the percentage change is signed wrong for the RBTC/XUSD pair (eg if the change is 1% it will show -1%). @soulBit let's maybe discuss this?
https://sovryn.atlassian.net/browse/SOV-1954
=> SOV-1954: Pair Selector price change issue
