- src/app/components/Footer/index.tsx
Do not load matomo tracker iframe if it was blocked by adblocker or brave browser
> Fixes empty iframe body in footer for brave browser

- src/app/components/ActiveBorrowTable/CollateralAmount.tsx
- src/app/components/BorrowActivity/Loadable.tsx
- src/app/components/BorrowActivity/index.tsx
- src/app/containers/BorrowHistory/Loadable.tsx
- src/app/containers/BorrowHistory/index.tsx
- src/app/containers/LendBorrowSovryn/index.tsx
- src/app/hooks/useGetContractPastEvents.ts
- src/locales/en/translation.json
- src/store/global/events-store/saga.ts
- creating as draft until database with Borrow event is up.
> Borrowing history

- src/styles/sass/_wallet-tutorial.scss
Change the price used in the Active Loan table to the amm price
> Changed position of coming soon sticker

- src/app/containers/LendBorrowSovryn/components/CurrencyContainer/CurrencyRow.tsx
Hope this is an acceptable solution
> Remove ellipsize from CurrencyRow titles for #165

- src/app/components/FormSelect/index.tsx
- src/app/components/Header/index.tsx
- src/app/containers/TradingPairSelector/index.tsx
- src/utils/helpers.ts
- removes auto focus to search field on selectors for mobile browsers (fix #221)
- fixes #145 - path to stats page is not translated anymore
> Fixes for mobile browsers

- src/app/components/FormSelect/index.tsx
- src/app/components/Header/index.tsx
- src/app/containers/TradingPairSelector/index.tsx
- src/utils/helpers.ts
Reverts DistributedCollective/Sovryn-frontend#242
> Revert "Fixes for mobile browsers"

- src/app/containers/TopUpTradingPositionHandler/index.tsx
Wasn't able to reproduce issue again, so hopefully this commit will fix it.
> maybe fixes #239

- .env.example
- .env.local
- .env.mainnet.local
- .env.production
- .env.testnet
- src/app/containers/MarginTradeForm/index.tsx
- src/app/containers/SalesPage/index.tsx
- src/app/containers/SwapTradeForm/index.tsx
- src/app/containers/TopUpTradingPositionHandler/index.tsx
- src/app/containers/TradingPage/index.tsx
- src/app/containers/WalletConnector/index.tsx
- src/styles/global-styles.ts
- src/utils/classifiers.ts
- src/utils/helpers.ts
Genesis sale preparations, trade/swap restrictions from env instead of hardcoded to mainnet, fixes #238
> Genesis sale preparations

- src/app/containers/SendBTC/index.tsx
* Fix #249, Pre-order instead of Sale in banner.
* Changed button in SOV for BTC sale tab
* Removed ununsed import
> Fix/brand fixes (#258)

- src/app/containers/SalesPage/screen2/index.tsx
* fixes #266
* removed unused import
> fixes #266 (#268)

- src/app/containers/LendBorrowSovryn/BorrowingContainer/index.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/pt_br/translation.json
Please ask Spanish/Brazilian Portuguese translators to confirm the text I added for those languages!
> Update text for #144

- src/app/components/NotificationForm/NotificationFormComponent/index.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/pt_br/translation.json
Added requested missing translation string - https://github.com/DistributedCollective/Sovryn-frontend/pull/317#issuecomment-770430886
Also fixed a spelling mistake in one of the prop names
> Add missing translation strings for #143

- src/app/components/CurrentPositionProfit/index.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/pt_br/translation.json
Add translation strings requested here: https://github.com/DistributedCollective/Sovryn-frontend/issues/143#issuecomment-770941031
> Add CurrentPositionProfit translation strings

- src/app/containers/MarginTradeForm/TradeConfirmationDialog.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/pt_br/translation.json
Add translation string requested here https://github.com/DistributedCollective/Sovryn-frontend/issues/143#issuecomment-771746234
Also added missing translation strings to the Spanish json file
> Translation string updates

- src/app/containers/FastBtcDialog/_overlayfix.scss
- src/app/containers/FastBtcDialog/index.module.css
- src/app/containers/FastBtcDialog/index.tsx
> Fix overlay for fast btc dialog covering scrollbar, added close button

- src/app/containers/SwapTradeForm/index.tsx
- src/locales/en/translation.json
@creed-victor it will reset amount to 0 when switching tokens, since user most likely will need to adjust balance anyway - see what you think.
I also set BTC -> DOC as default pair
> Implement Swap Form switch assets button for #450

- src/app/containers/FastBtcDialog/components/TransactionScreen.tsx
- src/locales/en/translation.json
> New FastBTCDialog translation strings for #457

- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/pt_br/translation.json
> Update Lend/borrow header link text to "Loans". Closes #485

- src/app/components/Header/index.tsx
Signed-off-by: shoeb <shoebsd31@gmail.com>
I searched through all the files for where target is blank and added the attribute rel="noreferrer noopener"
> #494 added rel=noreferrer noopener when target is blank

- src/app/containers/CloseTradingPositionHandler/index.tsx
> Disable repay position button when low liquidity. Closes #474

- src/app/containers/StatsPage/components/AmmBalance.tsx
- src/app/containers/StatsPage/index.tsx
- src/app/containers/StatsPage/types.ts
- src/app/containers/StatsPage/utils.ts
This is just an extra table on the stats page with amm balances
> Amm balances on stats page

- src/app/components/Footer/index.tsx
- src/app/components/MetaMaskDiscouragementNotifyModal/index.tsx
> Update tutorial modal wiki links, footer wiki link to match

- src/app/containers/LiquidityMining/components/EventTable.tsx
- src/app/containers/LiquidityMining/components/PoolData.tsx
- src/app/containers/StatsPage/components/AmmBalance.tsx
- src/app/containers/StatsPage/components/TVL.tsx
- src/app/containers/StatsPage/index.tsx
- src/app/containers/StatsPage/types.ts
- src/locales/en/translation.json
Some small changes to the stats page to include SOV amm balances and new endpoint for tvl data.
There may be another PR from this branch in the morning
> New stats to include SOV

- src/app/components/Footer/index.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/pt_br/translation.json
Could not test this on localhost. No GA there
> Switch matomo opt-out to ga opt-out

- src/locales/fr/translation.json
- src/locales/i18n.ts
Ajout de la traduction française
Premier jet, surement des modifications nécessaire.
Add french translation
First commit, maybe need some fix
> :globe_with_meridians: Typo : Add french translation

- src/locales/en/translation.json
> Fix typo in initial notification dialog

- src/app/components/Header/index.tsx
- src/assets/images/iconNewTab.svg
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/fr/translation.json
- src/locales/pt_br/translation.json
- create new dropdown group named Bitocracy
- move Stake and Governance navlinks to Bitocracy dropdown
- Make Stake and Governance dropdowns open in the new tab again
- Add icon which means that link will open in the new tab
- Do same thing for bitocracy.sovryn.app
- Open dropdowns on hover instead of click
> [Header] - added fixes for #755

- src/app/components/TradingChart/index.tsx
Tradingview requested we add their copyright text/link to our charts - @t-z-u can you review styling and confirm if it's ok?
> Add Tradingview chart attribution

- src/app/containers/LiquidityMining/components/RewardPool.tsx
> Fixes wrong reward pool endpoint

- src/utils/display-text/format.ts
> fix stringToFixedPrecision issue.

- src/app/components/TradeProfit/index.tsx
- src/app/hooks/trading/useMarginTrade.ts
- src/app/hooks/useFetch.ts
- src/app/hooks/useSendContractTx.ts
- src/app/pages/BuySovPage/components/InfoBar/index.tsx
- src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
- src/app/pages/MarginTradePage/components/TradingHistory/index.tsx
profit calculation bug fixes; increased margin trade gas fee; sov circulating supply updates from  backend
> Profit calculation bug fixes

- src/app/components/TradingChart/streaming.ts
Prevents chart from refreshing whilst window is unfocused
> Chart refresh on window focus

- src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
- src/app/pages/MarginTradePage/components/OpenPositionsTable/OpenPositionRow.tsx
> use existing liquidation price in margin dialog.

- src/app/components/Arrows/ArrowDown.tsx
- src/app/components/ComparisonChart/index.tsx
- src/app/components/FinanceV2Components/LootDrop/index.tsx
- src/app/components/FinanceV2Components/LootDrop/styled.ts
- src/app/components/Footer/index.tsx
- src/app/components/Form/AmountInput/index.tsx
- src/app/components/MobileBrowsersWarningDialog/index.tsx
- src/app/pages/LiquidityMining/components/AddLiquidityDialog/AddLiquidityDialogV1.tsx
- src/app/pages/LiquidityMining/components/AddLiquidityDialog/index.tsx
- src/app/pages/LiquidityMining/components/MiningPool/PoolAssetInfo.tsx
- src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
- src/app/pages/LiquidityMining/components/MiningPool/index.tsx
- src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/RemoveLiquidityDialogV1.tsx
- src/app/pages/LiquidityMining/components/RemoveLiquidityDialog/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
- src/app/pages/RewardPage/components/ClaimForm/index.tsx
- src/locales/en/translation.json
- src/styles/tailwindcss/components/form-group.css
- src/styles/tailwindcss/components/slider.css
- tailwind.config.js
> Restyle updates

- src/app/components/Form/AddressQrCode/index.tsx
> change AddressQrCode copy success.

- src/app/containers/SpotHistory/index.tsx
- src/app/containers/SwapHistory/index.tsx
- src/app/pages/RewardPage/components/RewardHistory/index.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
Also includes PT_BR translations from here:
https://github.com/DistributedCollective/Sovryn-frontend/pull/1163
> Translation strings. Closes #1068, closes #721

- src/app/components/FinanceV2Components/TableTransactionStatus/index.tsx
- src/app/pages/LiquidityMining/components/HistoryTable/TableBody/index.tsx
- src/app/pages/LiquidityMining/components/HistoryTable/TableRow/index.tsx
- src/app/pages/LiquidityMining/components/HistoryTable/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/utils/dictionaries/assets-dictionary.ts
> Feat/liquidity history 1120 

- src/app/pages/OriginsLaunchpad/components/EmailSubscribeSection/index.tsx
- src/app/pages/OriginsLaunchpad/components/EmailSubscribeSection/types.ts
- src/app/pages/OriginsLaunchpad/index.tsx
- src/locales/en/translation.json
note: name field in the form was in the task request i got from marketing team.
> autopilot email subscription

- src/app/containers/StatsPage/components/TVL.tsx
- src/app/containers/StatsPage/types.ts
- src/locales/en/translation.json
Add staked SOV to TVL table on stats page - currently total TVL figures do not include the new value, we need to let @BetsyBraddock know once this is deployed to mainnet so she can update backend endpoints at the same time
> [Stats page] Add staked SOV to TVL

- src/app/containers/StakePage/components/WithdrawVesting.tsx
- src/app/containers/StakePage/index.tsx
- src/utils/blockchain/requests/vesting.ts
Resolves issue where users are unable to withdraw vested Genesis SOV after unlocking
> Resolve issue withdrawing vested tokens

- src/app/containers/MaintenancePage/index.tsx
- src/app/containers/StakePage/components/DelegateForm.tsx
- src/app/containers/StakePage/components/ExtendStakeForm.tsx
- src/app/containers/StakePage/components/IncreaseStakeForm.tsx
- src/app/containers/StakePage/components/StakeForm.tsx
- src/app/containers/StakePage/components/WithdrawConfimationForm.tsx
- src/app/containers/StakePage/components/WithdrawForm.tsx
- src/app/containers/StakePage/components/WithdrawVesting.tsx
- src/app/index.tsx
- src/locales/en/translation.json
Adds maintenance mode to staking modals
> [Staking] Add maintenance to modals

- src/app/components/FinanceV2Components/CardRow/index.tsx
- src/app/components/FinanceV2Components/ComparisonChart/index.tsx
- src/app/components/FinanceV2Components/RowTable/index.tsx
- src/app/pages/LiquidityMining/components/MiningPool/PoolChart.tsx
- src/app/pages/LiquidityMining/components/MiningPool/index.tsx
- src/app/pages/LiquidityMining/components/MiningPool/types.ts
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
Currently testnet data is not available from backend, so this needs to be tested on mainnet (or staging link)
> [Yield Farm] Add history charts for pool AER

- src/locales/pt_br/translation.json
> Fix broken translation file

- src/app/containers/StatsPage/components/TVL.tsx
Users have reported display issues with TVL stats when connection is slow/fails. @t-z-u I can show you how to test this
> [Stats] Fix TVL display issue on slow connections

- src/app/hooks/useReserveWeight.ts
- src/app/pages/LiquidityMining/components/MiningPool/PoolAssetInfo.tsx
- src/app/pages/LiquidityMining/components/MiningPool/index.tsx
> [YieldFarm] - fixed 'unmounted components' errors

- src/app/components/AssetWalletBalance/index.tsx
- src/app/components/FinanceV2Components/ComparisonChart/Chart.tsx
- src/app/components/FinanceV2Components/ComparisonChart/index.tsx
- src/app/components/FinanceV2Components/LootDrop/index.tsx
- src/app/components/Spinner/index.tsx
- src/app/containers/RepayPositionHandler/RepayPositionForm.tsx
- src/app/containers/RepayPositionHandler/index.tsx
- src/app/containers/WalletPage/index.tsx
- src/app/hooks/useReserveWeight.ts
- src/app/pages/BorrowPage/BorrowingContainer/index.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/PoolChart.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/index.tsx
- src/app/pages/LendingPage/components/HistoryTable/TableBody/index.tsx
- src/app/pages/LendingPage/components/LendingDialog/index.tsx
- src/app/pages/LendingPage/index.tsx
- src/app/pages/LendingPage/types.ts
- src/app/pages/LiquidityMining/components/MiningPool/PoolAssetInfo.tsx
- src/app/pages/LiquidityMining/components/MiningPool/index.tsx
- src/app/pages/LiquidityMining/components/RowTable/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/styles/sass/_custom-styles.scss
- src/utils/blockchain/contracts.testnet.ts
- src/utils/helpers.ts
Merges latest release into development branch
> Master to development

- src/app/hooks/lending/useLending_balanceOf.ts
Small issue with dust remaining in rBTC pool when withdrawing full balance from pool
> [useLending_balanceOf] Fix silent errors when retrieving pool balances

- src/locales/pt_br/translation.json
Add new strings from this PR: https://github.com/DistributedCollective/Sovryn-frontend/pull/1507
> Add new strings to PT-BR

- src/app/containers/StakePage/components/HistoryEventsTable.tsx
Fixes translations for `Increase Stake` and `Extend Stake` on Staking history
> [Stake History] Increase/extend stake translations

- src/app/components/Header/index.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
- src/locales/pt_br/translation.json
Localisations from #1546 and two small fixes for Header & Lend
> Lend reward copy

- src/locales/pt_br/translation.json
Added the string of: https://github.com/DistributedCollective/Sovryn-frontend/pull/1549
> Add new string PT-BR

- src/utils/blockchain/contracts.testnet.ts
- src/utils/blockchain/contracts.ts
> Removes dummy MOC lending contract

- src/app/pages/LendingPage/index.tsx
- src/app/pages/LiquidityMining/index.tsx
https://taiga.sovryn.app/project/sovryn-light/task/67
> Update loot drop promos date

- src/app/containers/StakePage/components/VestingContract.tsx
- src/app/containers/StakePage/components/WithdrawVesting.tsx
- src/app/containers/VestedHistory/index.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/UserLendingInfo.tsx
- src/app/pages/LendingPage/index.tsx
- src/app/pages/LiquidityMining/hooks/useLiquidityMining_getPoolId.ts
- src/app/pages/LiquidityMining/hooks/useLiquidityMining_getUserInfoList.ts
- src/app/pages/LiquidityMining/index.tsx
- src/app/pages/SpotTradingPage/index.tsx
- src/locales/en/translation.json
Includes changes from #1480, #1577, and updated Loot Drop promo recalibration dates
> Release august 9

- src/app/pages/RewardPage/components/ClaimForm/index.tsx
- yarn.lock
> Disable claim button on reward SOV when tx is in progress

- src/utils/classifiers.ts
https://taiga.sovryn.app/project/sovryn-light/issue/171
> Increase CLOSE_WITH_SWAP gas limit to 1.5M

- src/app/components/LinkToExplorer/index.tsx
- src/app/pages/BridgeDepositPage/components/AmountSelector/index.tsx
- src/app/pages/BridgeDepositPage/components/ConfirmStep/index.tsx
- src/app/pages/BridgeDepositPage/components/UserWallet/index.tsx
- src/app/pages/BridgeDepositPage/components/WalletSelector/index.tsx
- src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-eth.mainnet.ts
- src/app/pages/BridgeDepositPage/dictionaries/assets/rsk-to-eth.testnet.ts
- src/app/pages/BridgeDepositPage/index.tsx
- src/app/pages/BridgeWithdrawPage/components/AmountSelector/index.tsx
- src/app/pages/BridgeWithdrawPage/components/TokenSelector/TokenItem.tsx
- src/app/pages/BridgeWithdrawPage/index.tsx
- src/locales/en/translation.json
- src/utils/classifiers.ts
- src/utils/metamaskHelpers.ts
- shows receiver wallet (wallet originally connected to rsk chain) in deposit flow
- shows currently connected (rsk) wallet in withdrawal flow
- changes "available balance" with "max withdrawal" in withdraw flow
> Show connected user wallet address in babelfish flows

- src/app/pages/LendingPage/components/HistoryTable/TableBody/index.tsx
- src/app/pages/LendingPage/types.ts
Resolves https://taiga.sovryn.app/project/sovryn-light/issue/278
> [LendingPage] fix HistoryTable timestamp type mismatch

- src/app/components/StakingDateSelector/index.tsx
- src/app/containers/StakePage/components/IncreaseStakeForm.tsx
- src/app/containers/StakePage/components/StakeForm.tsx
- src/app/hooks/staking/useStakeIncrease.ts
- src/app/hooks/staking/useStakeStake.ts
https://taiga.sovryn.app/project/sovryn-light/issue/304
> fix for max staking date

- src/app/components/UserAssets/useVestedStaking_balanceOf.ts
https://taiga.sovryn.app/project/sovryn-light/issue/305
> [Portfolio VestedAssets] Fix undefined Fish token

- src/locales/pt_br/translation.json
Add and translate new strings from PR: https://github.com/DistributedCollective/Sovryn-frontend/pull/1575 and https://github.com/DistributedCollective/Sovryn-frontend/pull/1577
> Add and translate new strings to PT-BR

- src/app/containers/VestedHistory/index.tsx
Resolves issue with vested history dates appearing as "01/01/1970"
> [Portfolio Vested History] Fix dayjs issue

- .eslintrc.js
- package.json
- yarn.lock
Fixes Storybook, to be able to run and be build again.
> [Storybook] update dependencies and eslints settings for storybook

- src/app/components/Form/AddressQrCode/index.tsx
- src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
Issue: https://taiga.sovryn.app/project/sovryn-light/issue/335
> Fix minReturn on swaps

- src/app/containers/StakePage/components/CurrentStakes.tsx
- src/app/containers/StakePage/components/ExtendStakeForm.tsx
- src/app/containers/StakePage/components/IncreaseStakeForm.tsx
- src/app/containers/StakePage/components/StakeForm.tsx
- src/app/containers/StakePage/components/WithdrawForm.tsx
- src/app/containers/StakePage/index.tsx
- src/styles/tailwindcss/components.css
+ fix error in console with forfeit
> [Staking] - fix the issue with stake/unstake 100% of SOV

- .storybook/main.js
- .storybook/preview.js
- .storybook/webpack.config.js
- src/app/components/Button/index.stories.tsx
- src/styles/tailwindcss/index.css
Resolves https://taiga.sovryn.app/project/sovryn-light/task/358.
Had to add a custom webpack config for storybook, that enables postcss 8, which is required for tailwind to work.
> [Storybook] tailwind for storybook

- src/utils/dictionaries/lending-pool-dictionary.ts
https://taiga.sovryn.app/project/sovryn-light/us/412
> feat: add SOV as collateral for borrowing

- src/locales/pt_br/translation.json
Added the strings from: https://github.com/DistributedCollective/Sovryn-frontend/pull/1704
> Add new strings PT-BR

- src/app/components/UserAssets/UnWrapDialog.tsx
- src/app/components/UserAssets/index.tsx
- src/app/containers/SwapFormContainer/index.tsx
- src/app/hooks/portfolio/useUnWrap.ts
- src/app/hooks/swap-network/useSwapNetwork_approveAndConvertByPath.ts
- src/app/hooks/swap-network/useSwapNetwork_conversionPath.ts
- src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
- src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
- src/app/pages/MarginTradePage/components/TradeDialog/index.tsx
- src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
- src/locales/en/translation.json
- src/store/global/transactions-store/types.ts
- src/types/asset.ts
- src/utils/blockchain/abi/SovrynSwapNetwork.json
- src/utils/blockchain/contracts.testnet.ts
- src/utils/blockchain/contracts.ts
- src/utils/classifiers.ts
- src/utils/dictionaries/assets-dictionary.ts
* fix: bring back swaps using wrapped rbtc proxy
* fix: allow users to unwrap they wrbtc
> Fix/swaps fix (#1722)

- src/app/components/Pagination/index.module.scss
- src/app/components/Pagination/index.stories.tsx
- src/app/components/Pagination/index.tsx
- src/app/components/Pagination/index.utils.ts
Resolves https://taiga.sovryn.app/project/sovryn-light/task/274
Just refactored the Pagination to new standards and added a storybook.
Story at /storybook/?path=/story/atoms-pagination--basic
Should not affect any functionality and visually only slightly.
> Feat/274 Pagination

- src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_AmmDepthChart.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
- src/app/pages/PerpetualPage/index.tsx
- src/locales/en/translation.json
- src/utils/display-text/format.ts
Initial implementation of https://taiga.sovryn.app/project/sovryn-light/task/441
> Perpetual Contract Details

- src/app/containers/SpotHistory/index.tsx
- src/app/containers/SwapFormContainer/index.tsx
- src/app/pages/SpotTradingPage/components/TradeForm/index.tsx
- src/app/pages/SpotTradingPage/types.ts
Testing:
1. go to portfolio page, verify that your WRBTC balance is 0 (if not, then unwrap your wrbtc to rbtc so it would become 0)
2. swap rbtc to sov - verify that tx was successful
3. swap sov to rbtc - verify that tx was successful
4. go back to portfolio pafe, verify that WRBTC balance is still 0.
> feat: switch between swaps external and rbtc proxy

- src/app/components/TradingChart/index.tsx
- src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
- src/app/pages/MarginTradePage/components/TradeForm/index.tsx
- src/utils/dictionaries/trading-pair-dictionary.ts
- src/utils/models/trading-pair.ts
Testing:
1. go to margin trading page
2. select sov-xusd pair
3. verify that pair has only "LONG" button available
4. open position with SOV or XUSD as collateral, verify tx confirms
5. "add to margin" of opened sov-xusd pair, verify tx confirms
6. close position of opened sov-xusd pair, verify tx confirms
7. repeat 4-6 with another collateral (not used on step 4 already).
8. repeat 2-7 steps with pairs rbtc-sov, bpro-sov and sov-doc.
> SOV margin trading (long)

- src/app/components/MetaMaskDiscouragementNotifyModal/index.tsx
- src/locales/pt_br/translation.json
CHANGELOG:
- feat: remove metamask disclaimer modal (#1737)
- copy: pt-br translations (#1729)
> Release canditate

- src/locales/pt_br/translation.json
Only merge when https://github.com/DistributedCollective/Sovryn-frontend/pull/1758 be merged. 
@soulBit 
Thanks
> New strings PT-BR

- src/app/components/UserAssets/index.tsx
- src/app/pages/BridgeDepositPage/dictionaries/bridges/mainnet.ts
- src/app/pages/BridgeDepositPage/dictionaries/bridges/testnet.ts
Reverts DistributedCollective/Sovryn-frontend#1768
> Revert "hotfix: disable binance chain bridging"

- src/locales/pt_br/translation.json
Will close https://github.com/DistributedCollective/Sovryn-frontend/pull/1775
@tiltom
> Add new strings and translate to PT-BR

- src/app/pages/LandingPage/components/CryptocurrencyPrices/index.tsx
- src/locales/en/translation.json
! Make sure to sync with Betsy (do backend update too) when releasing this.
> fix: add copy to explain circulating supply calculation change

- src/app/containers/WalletConnector/index.tsx
- src/global.d.ts
- src/locales/en/translation.json
- src/utils/helpers.ts
Task: https://taiga.sovryn.app/project/sovryn-light/issue/620
> feat: enable browser based wallets for mobile devices

- src/locales/pt_br/translation.json
Add change of: https://github.com/DistributedCollective/Sovryn-frontend/pull/1854
@soulBit
> Change string PT-BR

- src/locales/pt_br/translation.json
Add strings of: https://github.com/DistributedCollective/Sovryn-frontend/pull/1781
> Add strings PT-BR of Pull 1781

- src/utils/blockchain/contracts.testnet.ts
- src/utils/blockchain/contracts.ts
https://taiga.sovryn.app/project/sovryn-light/issue/624
> fix: swap tx's showing WRBTC, tx's not appearing in spot history

- src/app/hooks/swap-network/useSwapNetwork_convertByPath.ts
- src/app/pages/BuySovPage/components/BuyForm/index.tsx
was passing wrong parameters to "Buy SOV" swap contract call.
> hotfix: transactions failing on buy sov page

- src/app/pages/LandingPage/components/Promotions/index.tsx
- src/app/pages/LendingPage/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/utils/classifiers.ts
https://taiga.sovryn.app/project/sovryn-light/issue/653
> feat: bump staking withdraw gas limit for HW users

- src/locales/pt_br/translation.json
Please merge @creed-victor. Thanks.
> New strings and translate to PT-BR

- src/app/pages/PerpetualPage/components/AccountFundingHistory/AccountFundingHistoryRow.tsx
- src/app/pages/PerpetualPage/components/OpenPositionsTable/PendingPositionRow.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
- src/app/pages/PerpetualPage/components/RecentTradesTable/components/RecentTablesRow/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/types.ts
Resolves https://taiga.sovryn.app/project/sovryn-light/task/439
Implements recent trades explorer link and fixes some minor issues.
> Feat/439 Perpetual Recent Trades

- src/app/pages/PerpetualPage/components/FundingPaymentsTable/FundingPaymentsRow.tsx
- src/app/pages/PerpetualPage/components/FundingPaymentsTable/index.tsx
- src/app/pages/PerpetualPage/hooks/graphql/useGetTraderEvents.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_FundingPayments.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_OpenPositions.ts
- src/locales/en/translation.json
> Funding Payments table data

- src/app/pages/PerpetualPage/components/ClosePositionDialog/components/TradeFormStep.tsx
- src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
- src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx
- src/app/pages/PerpetualPage/components/PairSelector/index.tsx
- src/app/pages/PerpetualPage/components/RecentTradesTable/components/RecentTablesRow/utils.ts
- src/app/pages/PerpetualPage/components/RecentTradesTable/context.tsx
- src/app/pages/PerpetualPage/index.tsx
Resolves https://taiga.sovryn.app/project/sovryn-light/task/444
> Feat/444 Perpetual Temporary Pair Selector

- src/app/components/Header/index.tsx
- src/locales/en/translation.json
https://taiga.sovryn.app/project/zero/us/25
> feat(labs): add link to zero in header(testnet only)

- src/locales/pt_br/translation.json
Hi @creed-victor, please merge this minor changes. Thanks
> Minor changes PT-BR

- src/utils/blockchain/abi/FeeSharingProxy.json
- src/utils/blockchain/contracts.ts
Use new AMM pool addresses from latest upgrade, and switch feeSharingProxy ABI to latest
> feat: new AMM pool addresses, feeSharingProxy ABI

- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
Closes https://taiga.sovryn.app/project/sovryn-light/task/690.
The calculation was adjusted according to the Vasili's original formula (Option 2): https://docs.google.com/document/d/1j70nX7q3G5V3NbR_HDYbz94oPjGMVow6abb5mRbrAXc/edit .
We should also add the check for cheating users later.
> Fix Total PnL in Leaderboard

- src/app/hooks/staking/useVesting_getTeamVesting.ts
https://taiga.sovryn.app/project/sovryn-light/issue/686
> Fix Team SOV vesting history

- src/app/pages/PerpetualPage/components/AmmDepthChart/index.tsx
- src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
- src/app/pages/PerpetualPage/components/FundingPaymentsTable/index.tsx
- src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
- src/app/pages/PerpetualPage/components/OpenPositionsTable/components/RowAction.tsx
- src/app/pages/PerpetualPage/components/OpenPositionsTable/index.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/index.tsx
- src/app/pages/PerpetualPage/components/RecentTradesTable/components/RecentTablesRow/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/locales/en/translation.json
Resolves https://taiga.sovryn.app/project/sovryn-light/task/697
> Feat/697 Perpetual Tooltips

- src/utils/blockchain/abi/FeeSharingProxy.json
- src/utils/blockchain/abi/StakingRewards.json
- src/utils/blockchain/abi/bzxAbi.json
Update ABI files related to Rubicon smart contract deployment
> feat: update sovryn protocol ABIs

- src/app/pages/PerpetualPage/components/TradingChart/datafeed.ts
- src/app/pages/PerpetualPage/components/TradingChart/helpers.ts
- src/app/pages/PerpetualPage/components/TradingChart/index.tsx
- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
- src/app/pages/PerpetualPage/index.tsx
- src/app/pages/PerpetualPage/utils/graphQlHelpers.ts
Resolves https://taiga.sovryn.app/project/sovryn-light/task/703
Will need to be used by the Competition page as well.
> Feat/703 Perpetuals Graph Fallback

- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/index.tsx
- src/locales/en/translation.json
Resolves https://taiga.sovryn.app/project/sovryn-light/task/706 .
> Rules section adjustments

- src/app/pages/PerpetualPage/components/PairSelector/index.tsx
Resolves https://sovryn.monday.com/boards/2182625239/pulses/2217639411
> Do not show leverage in PairSelector

- src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2182625239/pulses/2217615372
> Don't show text in TradeForm if wallet is not connected

- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2182625105/pulses/2217607300
> [Perpetual] update tooltips

- src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_queryPerpParameters.ts
- src/app/pages/PerpetualPage/utils/perpMath.ts
- src/app/pages/PerpetualPage/utils/perpUtils.ts
- src/locales/en/translation.json
Resolves https://taiga.sovryn.app/project/sovryn-light/task/705 .
> Fix leverage selector and max trade size

- src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
Resolves https://sovryn.monday.com/boards/2182625239/pulses/2233535927
> Fix ContractDetails row

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/types.ts
- src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/hooks/useClaimRewardSov.tsx
- src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
- src/app/pages/RewardPage/components/RewardTab/index.tsx
- src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
- src/app/pages/RewardPage/index.tsx
https://taiga.sovryn.app/project/sovryn-light/issue/675
> fix: use single tx for reward claiming

- src/app/pages/MarginTradePage/components/TradeForm/index.tsx
- src/utils/dictionaries/trading-pair-dictionary.ts
- src/utils/models/trading-pair.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2231505190
> Remove leverage from SOV margin trade

- .storybook/preview.js
Ignore the [Perpetuals] in the comments please :grimacing: been to long on that project
> [Storybook] add preview viewports and backgrounds

- src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
https://sovryn.monday.com/boards/2218344956/pulses/2279289668
> fix: remove duplicate lockedSOV calculation

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
- src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
- src/locales/en/translation.json
- src/utils/classifiers.ts
Contains PRs:
#2045
#2042
also bumps gas limit for claiming liquid SOV from rewards page
> Release 2022 02 15

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
- src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
- src/locales/en/translation.json
- src/utils/classifiers.ts
* chore: bump liquid sov reward claiming gas limit
* fix: remove duplicate lockedSOV calculation (#2045)
* [Rewards] - add Staking Rewards Validation
* chore: fix claim button width
Co-authored-by: pietro-maximoff <pietro.maxim.official@protonmail.com>
> Release 2022 02 15 (#2050) - Master to Development

- src/app/pages/PerpetualPage/components/ToastsWatcher/index.tsx
- src/app/pages/PerpetualPage/slice.ts
- src/app/pages/PerpetualPage/types.ts
- src/app/pages/PerpetualPage/utils/perpMath.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2287699393
> Prevent re-toasting

- src/locales/en/translation.json
- Added UI copy emphasizing to the user that they should only send to the FastBTC deposit address generated for them
- Fixed various typos and UI copy inconsistencies
> Update FastBTC UI copy and fix typos

- src/app/components/Checkbox/index.module.scss
- src/app/components/Checkbox/index.stories.tsx
- src/app/components/Checkbox/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2255710988
> Checkbox atomic component

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/types.ts
- src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
- src/app/pages/RewardPage/components/LiquidTab/index.tsx
- src/app/pages/RewardPage/hooks/useGetLiquidSovClaimAmount.ts
- src/app/pages/RewardPage/index.module.scss
- src/app/pages/RewardPage/index.tsx
- src/utils/blockchain/abi/StakingRewards.json
- src/utils/blockchain/contracts.testnet.ts
https://sovryn.monday.com/boards/2218344956/pulses/2382518712
> hotfix: upgrade staking rewards liquid withdrawals

- src/app/containers/StakePage/components/FeeBlock.tsx
- src/app/containers/StakePage/components/VestingContract.tsx
- src/app/containers/StakePage/components/WithdrawVesting.tsx
- src/app/containers/StakePage/index.tsx
- src/utils/blockchain/requests/staking.ts
- src/utils/blockchain/requests/vesting.ts
https://sovryn.monday.com/boards/2218344956/pulses/2293940106
> fix(staking): add missing tx confirmation modals

- src/app/components/Switch/index.module.scss
- src/app/components/Switch/index.stories.tsx
- src/app/components/Switch/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2263336228
> add switch atomic component

- src/app/components/UserAssets/index.tsx
- src/app/pages/FastBtcPage/components/Deposit/MainScreen.tsx
- src/app/pages/FastBtcPage/components/Withdraw/AddressForm.tsx
- src/app/pages/FastBtcPage/components/Withdraw/AmountForm.tsx
- src/app/pages/FastBtcPage/components/Withdraw/MainScreen.tsx
- src/app/pages/FastBtcPage/components/Withdraw/ReviewScreen.tsx
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2419523061
> feat: maintenance mode for FastBTC flow

- src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
Disable Reward SOV claiming when Staking contract is frozen or paused
> feat: disable Reward SOV claiming when staking contract paused

- src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2473900095
> fix: change rpc for ethereum network

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/app/containers/StakePage/index.tsx
- src/utils/classifiers.ts
https://sovryn.monday.com/boards/2218344956/pulses/2460234627
> [Header] - Bitocracy link in testnet Dapp menu pointing to tesnet site

- src/app/pages/PerpetualPage/components/OpenPositionsTable/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_OpenPositions.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2508572752
> Display all perpetual positions regardless of the active pair

- package.json
- src/app/pages/FastBtcPage/components/Withdraw/AddressForm.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
- src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
- yarn.lock
Part of: https://sovryn.monday.com/boards/2218344956/pulses/2262412398
Primary PR: https://github.com/DistributedCollective/bridge-dapp/pull/115
Linked "RBTC transfer" button to bridge dapp.
> feat(bridge): btcs -> rbtc transfers

- package.json
- src/app/pages/PerpetualPage/components/EditLeverageDialog/index.tsx
- src/app/pages/PerpetualPage/components/TradeDetails/index.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/ResultPosition.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/index.tsx
- src/utils/classifiers.ts
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2525725061
> Fix edit leverage action

- src/app/components/Switch/index.module.scss
- src/app/components/Switch/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2430716176
> [Switch] - switch cleanup

- package.json
- src/app/pages/PerpetualPage/components/EditMarginDialog/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2525727977
> Fix edit margin action

- src/app/components/Header/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2550610466
> feat: header link to mynt bonding curve

- src/app/components/RadioButton/index.module.scss
- src/app/components/RadioButton/index.stories.tsx
- src/app/components/RadioButton/index.tsx
- src/app/components/RadioButton/types.ts
https://sovryn.monday.com/boards/2218344956/pulses/2368699487
> [RadioButton] - add RadioButton component

- package.json
- src/app/components/NetworkRibbon/component/DetectionScreen.tsx
- src/app/pages/PerpetualPage/components/EditLeverageDialog/index.tsx
- src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/SlippageFormStep.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/index.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/types.tsx
- src/app/pages/PerpetualPage/components/TradeForm/components/ResultingPosition.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_calculateResultingPosition.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_executeTransaction.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_openTrade.ts
- src/app/pages/PerpetualPage/types.ts
- src/app/pages/PerpetualPage/utils/perpUtils.ts
- src/locales/en/translation.json
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2579703679
**TODO**:
> Market orders adjustments

- src/app/components/Form/ActionButton/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
- src/app/pages/RewardPage/components/Tab/index.tsx
- src/app/pages/RewardPage/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2592961204?doc_id=2593071016&userId=26728963
> [Rewards] - add data ids

- src/app/containers/StakePage/components/CurrentStakes.tsx
- src/app/containers/StakePage/components/HistoryEventsTable.tsx
- src/app/containers/StakePage/components/VestingContract.tsx
- src/app/containers/StakePage/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2587083807?doc_id=2587134688&userId=26728963
> [Stake] - add data ids

- src/app/components/Arbitrage/Arbitrage.tsx
- src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
- src/app/containers/SwapFormContainer/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2592952245?doc_id=2593014092&userId=26728963
> [Swap] - add data ids

- src/app/pages/BridgeWithdrawPage/components/ReviewStep/index.tsx
- src/locales/en/translation.json
https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2562680425
https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2563151197
> fix: staking page updates

- src/app/pages/OriginsClaimPage/components/ClaimForm/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2592962131?doc_id=2598571149&userId=26728963
> [Origins] - add data-id

- src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
- src/app/pages/PerpetualPage/components/ContractDetails/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/index.tsx
- src/app/pages/PerpetualPage/hooks/graphql/useGetTraderEvents.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_OrderHistory.ts
- src/app/pages/PerpetualPage/types.ts
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2383096004
> Order History adjustments

- src/app/components/FinanceV2Components/PieChart/styled.ts
- src/app/components/FormSelect/index.tsx
- src/app/components/LanguageToggle/index.tsx
- src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/app/pages/BuySovPage/components/Button/index.tsx
- src/app/pages/BuySovPage/components/EngageWallet/index.tsx
- src/app/pages/BuySovPage/components/Feature/index.tsx
- src/app/pages/BuySovPage/components/Features/StakeVote.tsx
- src/app/pages/BuySovPage/components/Features/index.tsx
- src/app/pages/BuySovPage/components/TopUpWallet/index.tsx
- src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
- src/app/pages/LandingPage/components/Promotions/components/PromotionCard/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2534862001
https://sovryn.monday.com/boards/2218344956/pulses/2534576285
https://sovryn.monday.com/boards/2218344956/pulses/2545855756
> feat: data attributes added

- src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
- src/utils/classifiers.ts
- src/utils/metamaskHelpers.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2640120495
> Perpetuals - update RPCs

- src/app/components/PairNavbar/Pair.tsx
- src/app/components/PairNavbar/PairCryptocurrency.tsx
- src/app/components/PairNavbar/PairSelect.tsx
- src/app/components/PairNavbar/index.tsx
- src/app/pages/SpotTradingPage/components/LimitOrderSetting/Duration.tsx
- src/app/pages/SpotTradingPage/components/LimitOrderTables/LimitOrderRow.tsx
- src/app/pages/SpotTradingPage/components/TradeForm/LimitForm.tsx
- src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
- src/app/pages/SpotTradingPage/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2592952727?doc_id=2598517876&userId=26728963
> [Spot] - add ids

- src/app/containers/StakePage/components/CurrentStakes.tsx
- src/app/containers/StakePage/components/DelegateForm.tsx
- src/app/containers/StakePage/index.tsx
- src/app/hooks/staking/useStaking_timestampToLockDate.ts
https://sovryn.monday.com/boards/2218344956/pulses/2539143747
> fix: use timestampToLockDate value instead of current timestamp to calculate voting power

- src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/TradeFormStep.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_isAddressWhitelisted.ts
- src/app/pages/PerpetualPage/slice.ts
- src/app/pages/PerpetualPage/types.ts
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2352195971
> Perpetuals - Whitelisting

- src/app/index.tsx
- src/app/pages/PerpetualPage/components/CustomToastContent/index.tsx
- src/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2639610651
> Fix perpetual toasts

- src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
- src/app/pages/PerpetualPage/hooks/graphql/useGetTraderEvents.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_OrderHistory.ts
- src/app/pages/PerpetualPage/types.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2623453964
> Show limit orders tx id in history tables

- src/app/containers/StakePage/components/FeeBlock.tsx
- src/app/containers/StakePage/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2587083807
> [Stake] - add data ids for fees withdraw btn

- src/app/pages/LandingPage/components/Promotions/index.tsx
- src/app/pages/LiquidityMining/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2706659913
> feat: update LM reward promos

- src/app/pages/PerpetualPage/components/TradeDialog/index.module.scss
- src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_analyseTrade.ts
- src/app/pages/PerpetualPage/utils/contractUtils.tsx
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2724954219
> Perpetuals small fixes

- src/app/components/NetworkRibbon/NetworkRibbon.tsx
- src/app/pages/PerpetualPage/components/OpenOrdersTable/index.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/OrderHistoryRow.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_OpenOrders.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_OrderHistory.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_analyseTrade.ts
- src/app/pages/PerpetualPage/utils/contractUtils.tsx
- src/locales/en/translation.json
- src/utils/dictionaries/perpetual-pair-dictionary.ts
- src/utils/models/perpetual-pair.ts
Resolves https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2735915001
> Fix small perpetual issues vol. 2

- src/app/pages/FastBtcPage/config/contracts.ts
https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2736121110
> feat(btcs): change testnet contracts to support gsn

- src/app/pages/PerpetualPage/contexts/RecentTradesContext.tsx
- src/app/pages/PerpetualPage/types.ts
- src/utils/blockchain/contracts.testnet.ts
Part of https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2754311875
> Perpetuals - new deployment

- src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/TradeFormStep.tsx
- src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_calculateResultingPosition.ts
- src/app/pages/PerpetualPage/utils/contractUtils.tsx
Resolves https://sovryn.monday.com/boards/2218344956/views/53321005/pulses/2754311875
> Perpetuals - bug fixes vol. 3

- package.json
- yarn.lock
This PR resolves https://sovryn.monday.com/boards/2218344956/pulses/2725103061 and is a cherry picked version of #2231 targeting `master` branch
> [Portis] - fix transactions issue

- src/app/components/Checkbox/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_analyseTrade.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2773526353
> Perpetuals fixes

- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
- src/app/pages/PerpetualPage/types.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2754323128
> Perpetuals - use new subgraph

- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
- src/app/pages/PerpetualPage/hooks/graphql/useGetLeaderboardData.ts
Partially resolves https://sovryn.monday.com/boards/2218344956/pulses/2754323128
> Use new subgraph for Leaderboard

- src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/fr/translation.json
- src/locales/pt_br/translation.json
- src/utils/blockchain/abi/sovrynProtocol.json
Contains changes from https://github.com/DistributedCollective/Sovryn-frontend/pull/2234, and also contains new ABI change for sovrynProtocol contract
> Remove FAQ / new sovrynProtcol ABI

- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2804327694
> Perpetuals leaderboard adjustments

- src/app/components/Form/FormGroup/index.tsx
- src/app/pages/PerpetualPage/components/FundingPaymentsTable/index.tsx
- src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
- src/app/pages/PerpetualPage/components/OrderHistoryTable/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2804311642 (bugs will be fixed in a separate PR).
> Perpetuals - adjust tooltips

- src/app/pages/PerpetualPage/types.ts
- src/locales/en/translation.json
- src/utils/blockchain/contracts.testnet.ts
https://sovryn.monday.com/boards/2218344956/pulses/2810198119
> chore: change perpetual contract addresses

- public/index.html
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2792391375
Supercedes #2258 (we are merging this together with other changes in `development` for release)
> feat: add perps comp popup

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/app/containers/StakePage/components/HistoryEventsTable.tsx
- src/app/containers/WalletConnector/index.module.scss
- src/app/containers/WalletConnector/index.tsx
- src/utils/helpers.ts
* fix: ZUSD reward rate
* fix: stake history table crashing
* feat: wallet menu QoL updates
> Feat/2822193594 qol said the raven (#2271) -> development

- src/app/components/HeaderLabs/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2821592649
> Perpetuals - minor adjustments

- src/app/components/TradingChart/datafeed.ts
- src/app/index.tsx
- src/locales/pt_br/translation.json
Contains changes:
- Chunk data requests for trading charts to improve performance in #2276
- Multiple PT_BR localizations from @bitcoinuser in #2268
> Chunk Data requests (#2276), PT_BR localizations (#2268)

- src/app/components/TradingChart/datafeed.ts
- src/app/index.tsx
- src/locales/pt_br/translation.json
* New strings PT-BR (#2268)
* Fix/2829091249 chunk chart data (#2276)
Co-authored-by: bitcoinuser <bitcoinuser@users.noreply.github.com>
> Sync master -> dev

- package.json
- src/app/pages/PerpetualPage/components/TradingChart/streaming.ts
- src/app/pages/PerpetualPage/contexts/RecentTradesContext.tsx
- src/app/pages/PerpetualPage/utils/contractUtils.tsx
- src/utils/blockchain/abi/PerpetualManager.json
- src/utils/blockchain/contracts.testnet.ts
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2841502913
> Perpetuals - deployment update

- src/app/pages/PerpetualPage/components/DataCard/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/TradeFormStep.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.module.scss
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_analyseTrade.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2859863296
> Perpetuals - design adjustments

- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
- src/app/pages/PerpetualPage/hooks/graphql/useGetCandles.ts
- src/app/pages/PerpetualPage/types.ts
- src/utils/blockchain/contracts.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2861869933
> Perpetuals - staging deployment preparation

- src/app/pages/PerpetualPage/components/NewPositionCard/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
- src/app/pages/PerpetualPage/types.ts
- src/app/pages/PerpetualPage/utils/contractUtils.tsx
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2878534004
> Perpetuals - close only limit orders

- src/locales/en/translation.json
https://sovryn.monday.com/boards/2218344956/pulses/2892239961
> feat: update XUSD lend pool reward promo

- src/app/components/Input/index.tsx
- src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
- src/app/pages/PerpetualPage/components/GsnSwitch/GsnSwitch.tsx
- src/app/pages/PerpetualPage/components/LayoutMenu/index.tsx
- src/app/pages/PerpetualPage/components/LeverageSelector/index.tsx
- src/app/pages/PerpetualPage/components/OpenOrdersTable/components/OpenOrderRow.tsx
- src/app/pages/PerpetualPage/components/OpenPositionsTable/components/OpenPositionRow.tsx
- src/app/pages/PerpetualPage/components/PairSelector/PairSelectorButton.tsx
- src/app/pages/PerpetualPage/components/TableRowAction/index.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2880763296
> Perpetuals - add data action ids

- src/app/pages/PerpetualPage/components/AccountBalanceCard/index.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
- src/app/pages/PerpetualPage/components/AmmDepthChart/AmmDepthChartRow.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/TradeSummary.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/utils/metamaskHelpers.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2907940578
> Perpetuals - final fixes before mainnet competition

- src/app/hooks/useMaintenance.ts
- src/app/pages/MarginTradePage/components/TradeForm/index.tsx
> Master to dev 2022-07-11

- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2753800110
> Perpetuals - adjust subgraph healtcheck + fix errors

- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/contexts/GraphQLProvider.tsx
Resolve issue with failing subgraph heathcheck
> Perpetuals - adjust subgraph healtcheck + fix errors (#2321)

- src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
- src/utils/blockchain/networks.json
- src/utils/classifiers.ts
- src/utils/metamaskHelpers.ts
Resolves websocket/RPC issue with BSC chain
> Perpetuals - update websockets and RPC configuration (#2323)

- src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2929191683
> Perpetuals - temporary change of testnet bridge link

- src/app/hooks/useGsnSendTx.ts
- src/app/hooks/useSendContractTx.ts
- src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
- src/locales/en/translation.json
- src/store/global/transactions-store/types.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2935404867
> Perpetuals - display correct error message when the balance is not enough for GSN gas

- src/app/hooks/useGsnSendTx.ts
- src/app/hooks/useSendContractTx.ts
- src/app/pages/FastBtcPage/containers/DepositContainer.tsx
- src/app/pages/PerpetualPage/components/AccountBalanceForm/index.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/ConfirmationStep.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
- src/store/global/transactions-store/types.ts
* Perpetuals failed transactions due to funds not available to pay gas costs by @tiltom in #2328 
* FastBTC deposit signature verification fix for new wallets by @soulBit in #2330
> Release 2022-07-13

- src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/RegisterDialog/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_isAddressWhitelisted.ts
- src/app/pages/PerpetualPage/hooks/usePerpetual_transaction.ts
- src/locales/en/translation.json
* Adjust gas price estimation
* Disable whitelist
* Add RegisterDialog
* Enforce minimum order size in limit orders
* Open quickstart guide in a new tab
> Perpetuals - remove whitelist (#2332)

- package.json
- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/CompetitionEndCountdown/index.tsx
- src/locales/en/translation.json
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2939797872
> Perpetuals - competition countdown

- package.json
- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_getAmmCompetitionProfit.ts
- src/locales/en/translation.json
- src/utils/blockchain/abi/lpShareToken.json
- src/utils/blockchain/contracts.testnet.ts
- src/utils/blockchain/contracts.ts
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2940062165
> Perpetuals - Show potential competition prizes

- package.json
- src/app/components/UserAssets/Vesting/VestedItem.tsx
- src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
- src/app/components/UserAssets/components/BridgeLink.tsx
- src/app/components/UserAssets/components/UserAssetsTableRow.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/CompetitionEndCountdown/index.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
- src/app/pages/PerpetualPage/components/NewPositionCard/components/ConnectFormStep.tsx
- src/app/pages/PerpetualPage/components/TradeDialog/components/ReviewStep.tsx
- src/app/pages/PerpetualPage/components/TradeForm/index.tsx
- src/app/pages/PerpetualPage/hooks/usePerpetual_getAmmCompetitionProfit.ts
- src/app/pages/PortfolioPage/index.tsx
- src/locales/en/translation.json
- src/utils/blockchain/abi/lpShareToken.json
- src/utils/blockchain/contracts.testnet.ts
- src/utils/blockchain/contracts.ts
- yarn.lock
Contains changes from:
#2307 
#2335 
#2337 
#2338
> Release 2022-07-15

- src/app/pages/PerpetualPage/hooks/usePerpetual_ContractDetails.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2949036583
> Perpetuals - fix 24h volume bug

- src/app/pages/PerpetualPage/PerpetualPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/CompetitionPageContainer.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/TraderRow.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/Leaderboard/index.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/RegisterDialog/index.tsx
- src/locales/en/translation.json
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2951111674
> Perpetuals - UI changes for end of the mainnet competition

- src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
- src/app/pages/PerpetualPage/utils/contractUtils.tsx
- src/utils/blockchain/networks.json
- src/utils/classifiers.ts
- src/utils/metamaskHelpers.ts
Resolves https://sovryn.monday.com/boards/2218344956/pulses/2949551365
> Perpetuals - configuration updates

- public/index.html
- src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
https://sovryn.monday.com/boards/2218344956/pulses/2946022453
> Update Cookie Consent bar and analytics Opt-out

- src/app/pages/BridgeDepositPage/index.tsx
- src/app/pages/BridgeWithdrawPage/index.tsx
Resolves confirm button overlapping table in cross-chain flow on smaller screen sizes
> fix: add margin to deposit cross chain

- public/index.html
- src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
> chore: revert cookie consent

- src/app/pages/FastBtcPage/components/Deposit/DepositDetails.tsx
- src/app/pages/RewardPage/components/LiquidTab/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/3041932736
> Formatting fixes

- src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
- src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/3043057253
> fix: margin trade contract call errors

- src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
https://sovryn.monday.com/boards/2218344956/pulses/3065754799
> fix: margin trade profit contract call

- src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
- src/app/pages/MarginTradePage/components/OpenPositionsTable/ProfitContainer.tsx
https://sovryn.monday.com/boards/2218344956/pulses/3082658156
> hotfix: margin trading pln calculation

- package.json
- src/index.tsx
- yarn.lock
https://sovryn.monday.com/boards/2218344956/pulses/3034125830?userId=26728963
> Remove rWallet and Nifty

- src/app/hooks/useMaintenance.ts
- src/locales/pt_br/translation.json
- src/store/global/maintenance-store/saga.ts
- src/store/global/maintenance-store/types.ts
- src/utils/classifiers.ts
- [Maintenance] - update maintenance url by @pietro-maximoff in #2211
> Release 2022-08-17

- package.json
- src/app/pages/PerpetualPage/components/AmmDepthChart/AmmDepthChartRow.tsx
- src/app/pages/PerpetualPage/contexts/PerpetualQueriesContext.tsx
- yarn.lock
Resolves https://sovryn.monday.com/boards/2218344956/pulses/3089006474
> Perpetuals - adjust AMM Depth chart

- src/app/components/Promotions/components/PromotionsCarousel/index.tsx
- src/app/components/Promotions/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
- src/utils/dictionaries/amm/mainnet.ts
- src/utils/dictionaries/amm/testnet.ts
https://sovryn.monday.com/boards/2218344956/pulses/3121070812
> feat: update promotions

- public/index.html
- src/app/components/Promotions/components/PromotionsCarousel/index.tsx
- src/app/components/Promotions/index.tsx
- src/app/containers/PageContainer/components/DefaultFooterComponent/DefaultFooterComponent.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
- src/utils/dictionaries/amm/mainnet.ts
- src/utils/dictionaries/amm/testnet.ts
- Update Reward SOV amounts for latest calibration on Yield Farm page by @Rickk137 in #2397 
- New cookie consent banner for Analytics opt-out by @soulBit in #2396
> Release 2022-08-22

- src/locales/en/translation.json
- src/locales/pt_br/translation.json
https://sovryn.monday.com/boards/2218344956/pulses/3088678181?doc_id=3088680652
> [Reward] - update text note in liquidClaimForm tab

- src/app/containers/VestedHistory/index.tsx
https://sovryn.monday.com/boards/2218344956/pulses/3159577746?doc_id=3159582823
> [Portfolio] - fix table header (when no data)

- README.md
- src/app/components/Promotions/index.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
- src/app/pages/LendingPage/index.tsx
https://sovryn.atlassian.net/browse/SOV-428
> feat: update XUSD lend pool rewards

- README.md
- src/app/components/Promotions/index.tsx
- src/app/containers/VestedHistory/index.tsx
- src/app/pages/LendingPage/components/CurrencyContainer/CurrencyRow.tsx
- src/app/pages/LendingPage/index.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
- yarn.lock
Contains changes from:
#2347
#2269 
#2400
#2401
#2402
#2405
> Release 2022-09-05

- src/app/pages/BridgeWithdrawPage/components/ReceiverSelector/index.tsx
- src/locales/en/translation.json
Resolves https://sovryn.atlassian.net/browse/SOV-444 .
> Fix text in the warning message for cross chain transfers

- src/app/pages/LandingPage/components/Banner/GetStartedBanner.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-670
> Hide perps banner on homepage

- src/app/pages/LandingPage/index.tsx
https://sovryn.atlassian.net/browse/SOV-734
> switch Zero TVL contract calls with backend query

- src/app/components/AssetValue/index.tsx
- src/app/components/RecentTrades/RecentSwapRow.tsx
- src/app/components/RecentTrades/RecentTradeRow.tsx
- src/app/components/RecentTrades/SwapTrades.tsx
- src/app/hooks/trading/useMargin_RecentTrades.ts
- src/app/hooks/trading/useSwap_RecentTrades.ts
- src/types/trading-pairs.ts
- src/utils/blockchain/contracts.testnet.ts
- src/utils/dictionaries/amm/testnet.ts
- src/utils/graphql/rsk/generated.tsx
- src/utils/graphql/rsk/operations/getRecentMarginEvents.graphql
- src/utils/graphql/rsk/operations/getRecentSwapEvents.graphql
- src/utils/helpers.ts
https://sovryn.atlassian.net/browse/SOV-543
> SOV-543: recent trades on graphql

- src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
- src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
https://sovryn.atlassian.net/browse/SOV-857
> feat: disable RBTC fee claiming on Rewards page

- src/app/hooks/useAssetBalanceOf.ts
Resolves https://sovryn.atlassian.net/browse/SOV-870
> Fix asset balances

- src/app/pages/BridgeDepositPage/components/WalletSelector/index.tsx
- src/app/pages/FastBtcPage/components/AggregatorWithdraw/NetworkStep.tsx
- src/utils/metamaskHelpers.ts
https://sovryn.atlassian.net/browse/SOV-864
> fix: switchNetwork BSC issue

- src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
https://sovryn.atlassian.net/browse/SOV-907
> feat: enable RBTC fee claiming in Rewards page

- src/app/components/TradingChart/index.tsx
https://sovryn.atlassian.net/browse/SOV-917
> fix: trading chart layout on mobile

- src/app/hooks/trading/usePairList.ts
Resolves https://sovryn.atlassian.net/browse/SOV-896
> Hide XUSD_legacy from margin trade

- src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-897
> Fix RBTC missing on Swap page

- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-962
> SOV-962 - chore: bump gaslimit for adding to lend pool txs

- src/app/components/NetworkRibbon/NetworkRibbon.tsx
- src/app/containers/PageContainer/PageContainer.tsx
- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/app/containers/PageContainer/types.ts
- src/app/index.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1107
> Remove Perpetuals page from navigation

- src/app/components/NetworkRibbon/NetworkRibbon.tsx
- src/app/containers/PageContainer/PageContainer.tsx
- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/app/containers/PageContainer/types.ts
- src/app/containers/SwapFormContainer/components/SwapSelector/index.tsx
- src/app/hooks/trading/usePairList.ts
- src/app/index.tsx
Contains changes from:
https://github.com/DistributedCollective/Sovryn-frontend/pull/2456 - sunset Perpetuals content
> Release 2022-11-30

- src/app/components/Form/AddressQrCode/index.tsx
- src/app/components/TransakDialog/TransakScreen.tsx
- src/app/components/TransakDialog/useTransak.ts
- src/app/pages/FastBtcPage/components/Deposit/AddressForm.tsx
- src/app/pages/FastBtcPage/components/Deposit/DepositDetails.tsx
- src/app/pages/FastBtcPage/components/Deposit/SidebarStepsDeposit.tsx
- src/app/pages/FastBtcPage/components/Deposit/SignatureValidation/index.tsx
- src/app/pages/FastBtcPage/components/FastBtcButton.tsx
- src/app/pages/FastBtcPage/containers/DepositContainer.tsx
- src/app/pages/FastBtcPage/index.tsx
- src/app/pages/FastBtcPage/types.ts
- src/app/pages/ReceiveRBTCPage/index.tsx
- src/locales/en/translation.json
https://sovryn.atlassian.net/browse/SOV-1141
> SOV-1141: fixing the transak integration

- src/app/components/Form/AddressQrCode/index.tsx
- src/app/components/TransakDialog/TransakScreen.tsx
- src/app/components/TransakDialog/useTransak.ts
- src/app/pages/FastBtcPage/components/Deposit/AddressForm.tsx
- src/app/pages/FastBtcPage/components/Deposit/DepositDetails.tsx
- src/app/pages/FastBtcPage/components/Deposit/SidebarStepsDeposit.tsx
- src/app/pages/FastBtcPage/components/Deposit/SignatureValidation/index.tsx
- src/app/pages/FastBtcPage/components/FastBtcButton.tsx
- src/app/pages/FastBtcPage/containers/DepositContainer.tsx
- src/app/pages/FastBtcPage/index.tsx
- src/app/pages/FastBtcPage/types.ts
- src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
- src/app/pages/ReceiveRBTCPage/index.tsx
- src/locales/en/translation.json
Contains changes from:
- #2461 
- #2462
> Release 2022-12-13

- src/app/pages/SpotTradingPage/types.ts
https://sovryn.atlassian.net/browse/SOV-1764
> SOV-1764 add dllr to spot trading pairs

- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-1897
> SOV-1897: Increase Liquid SOV claim gaslimit

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/LiquidClaimForm/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/RewardClaimForm/index.tsx
https://sovryn.atlassian.net/browse/SOV-1903
> SOV-1903: Reward SOV claiming using stakingRewardsProxy contract balance check

- src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
- src/app/pages/MarginTradePage/types.ts
- src/app/pages/SpotTradingPage/types.ts
https://sovryn.atlassian.net/browse/SOV-1865
> SOV-1865: Added subscription payload to notifications

- src/app/containers/SwapFormContainer/index.tsx
- src/app/hooks/tutorial/useGetMaximumAssetPrice.ts
- src/app/hooks/useDollarValue.ts
- src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
- src/locales/en/translation.json
Resolves https://sovryn.atlassian.net/browse/SOV-1457
> SOV-1457: Add maximum price to order forms

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/app/containers/WalletConnector/index.tsx
- src/app/index.tsx
- src/app/pages/PortfolioPage/index.tsx
- src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
- src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
- src/utils/blockchain/abi/FeeSharingProxy.json
https://sovryn.atlassian.net/browse/SOV-1510
> SOV-1510: update rewards page

- src/app/pages/SpotTradingPage/types.ts
https://sovryn.atlassian.net/browse/SOV-1810
> SOV-1810: DLLR the quote currency in the Spot trading

- src/app/pages/BridgeDepositPage/components/ReviewStep/index.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1404
> SOV-1404: Use correct target token in cross chain deposit flow

- src/app/containers/WalletConnector/index.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1874
> SOV-1874: Lowercase user address

- src/utils/blockchain/abi/VestingRegistry.json
Resolves https://sovryn.atlassian.net/browse/SOV-1751
> SOV-1751: Update VestingRegistry contract

- src/app/containers/WalletProvider/slice.ts
- src/app/containers/WalletProvider/types.ts
- src/app/pages/MarginTradePage/components/NotificationSettingsDialog/index.tsx
- src/app/pages/MarginTradePage/slice.ts
- src/app/pages/MarginTradePage/types.ts
- src/utils/metamaskHelpers.ts
Resolves https://sovryn.atlassian.net/browse/SOV-746
> SOV-746: Fix email notification settings dialog

- src/app/components/AddressBadge/index.tsx
- src/app/pages/FastBtcPage/components/Deposit/StatusScreen.tsx
- src/app/pages/FastBtcPage/containers/DepositContainer.tsx
- src/app/pages/FastBtcPage/contexts/deposit-context.ts
- src/utils/graphql/rsk/generated.tsx
- src/utils/graphql/rsk/operations/getFastBtcDepositRskTransaction.graphql
- src/utils/graphql/rsk/schema.graphql
Resolves https://sovryn.atlassian.net/browse/SOV-1761
> SOV-1761: Fix Fast BTC information

- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/utils/dictionaries/amm/testnet.ts
https://sovryn.atlassian.net/browse/SOV-1982
> SOV-1982: update "yield farming" banners

- src/utils/blockchain/contracts.ts
- src/utils/dictionaries/amm/mainnet.ts
Resolves:
https://sovryn.atlassian.net/browse/SOV-1877
https://sovryn.atlassian.net/browse/SOV-1635
https://sovryn.atlassian.net/browse/SOV-1633
> SOV-1877: D1 DLLR integration

- src/app/hooks/trading/useCachedAssetPrice.ts
Resolves https://sovryn.atlassian.net/browse/SOV-2041
> SOV-2041: Fix DLLR spot limit

- src/app/components/Promotions/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/pt_br/translation.json
- src/utils/dictionaries/amm/mainnet.ts
- src/utils/dictionaries/amm/testnet.ts
Resolves:
https://sovryn.atlassian.net/browse/SOV-2062
https://sovryn.atlassian.net/browse/SOV-2072
> Yield Farm Refactoring

- src/app/hooks/trading/useTrading_resolvePairTokens.ts
- src/app/hooks/useCacheCall.ts
- src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
- src/app/pages/MarginTradePage/components/SlippageForm/index.tsx
- src/app/pages/MarginTradePage/components/TradeForm/index.tsx
- src/app/pages/MarginTradePage/utils/marginUtils.ts
- src/locales/en/translation.json
Resolves https://sovryn.atlassian.net/browse/SOV-1867
> SOV-1867: Fix margin long slippage form

- src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
- src/store/global/transactions-store/types.ts
- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-2140
> SOV-2140: bump gaslimit for claiming RBTC fees

- src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
- src/app/pages/RewardPage/components/HistoryTable/index.tsx
- src/app/pages/RewardPage/components/LiquidTab/index.tsx
- src/app/pages/RewardPage/components/RewardTab/hooks/useGetAvailableLiquidityRewards.ts
- src/app/pages/RewardPage/components/RewardTab/index.tsx
- src/app/pages/RewardPage/components/RewardsDetail/index.tsx
- src/app/pages/RewardPage/hooks/useGetRewardSovClaimAmount.ts
- src/app/pages/RewardPage/hooks/useGetUserRewardsEarnedHistory.ts
- src/app/pages/RewardPage/index.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
- src/utils/blockchain/abi/LiquidityMining.json
- src/utils/graphql/rsk/generated.tsx
- src/utils/graphql/rsk/operations/getUserRewardsEarnedHistory.graphql
Resolves https://sovryn.atlassian.net/browse/SOV-2001
> SOV-2001: Update reward SOV page 

- src/app/components/TransactionDialog/hooks/useGetNormalizedError.ts
https://sovryn.atlassian.net/browse/SOV-2186
> fix: safari crashing because of unsupported regex

- src/app/components/Promotions/components/PromotionCard/index.module.scss
- src/app/components/Promotions/components/PromotionCard/index.tsx
- src/app/components/Promotions/components/PromotionCard/utils.tsx
- src/app/components/Promotions/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/locales/es/translation.json
- src/locales/fr/translation.json
- src/locales/pt/translation.json
- src/locales/pt_br/translation.json
https://sovryn.atlassian.net/browse/SOV-2021
> SOV-2021: update Promo cards display

- src/app/components/FinanceV2Components/utils/getAssetColor.ts
- src/app/hooks/lending/useGetLendingHistory.ts
- src/utils/blockchain/contracts.testnet.ts
- src/utils/dictionaries/lending-pool-dictionary.ts
https://sovryn.atlassian.net/browse/SOV-2161
https://sovryn.atlassian.net/browse/SOV-2160
> SOV-2160: DLLR Lend pool, use DLLR as collateral

- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/locales/pt/translation.json
- src/locales/pt_br/translation.json
- src/utils/dateHelpers.ts
https://sovryn.atlassian.net/browse/SOV-2250
> SOV-2250: update reward SOV promo amounts and recalibration date

- .env.local
- .env.mainnet.local
- .env.production
- .env.testnet
- codegen.fetch.yml
- codegen.yml
- netlify.toml
- src/app/pages/BridgeDepositPage/components/TokenSelector/TokenItem.tsx
- src/app/pages/BridgeDepositPage/components/TokenSelector/index.tsx
- src/app/pages/BridgeDepositPage/hooks/useGetPausedTokens.ts
- src/index.tsx
- src/utils/classifiers.ts
- src/utils/clients.ts
- src/utils/graphql/babelfish/generated.tsx
- src/utils/graphql/babelfish/operations/getPausedBassetList.graphql
- src/utils/graphql/babelfish/schema.graphql
Resolves https://sovryn.atlassian.net/browse/SOV-2028
> SOV-2028: Enforce Babelfish Aggregator pause state for tokens on Bridge

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
https://sovryn.atlassian.net/browse/SOV-2310
> SOV-2310: prevent internal redirect for external links on mobile header menu

- src/app/containers/SwapFormContainer/components/ReviewDialog/index.tsx
- src/app/containers/SwapFormContainer/index.tsx
- src/app/pages/BuySovPage/components/BuyForm/Dialogs/SlippageDialog.tsx
- src/app/pages/SpotTradingPage/components/TradeDialog/index.tsx
- src/app/pages/SpotTradingPage/components/TradeForm/MarketForm.tsx
- src/locales/en/translation.json
https://sovryn.atlassian.net/browse/SOV-2023
> SOV-2023: Show maximum price

- src/app/components/PairNavbarInfo/index.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-1811
> SOV-1811: Fix XUSD and DOC regression

- src/app/components/Promotions/hooks/useGetPromotionsData.ts
- src/app/components/Promotions/index.tsx
- src/app/components/Promotions/types.ts
- src/app/pages/LandingPage/index.tsx
- src/app/pages/LiquidityMining/index.tsx
- src/locales/en/translation.json
- src/locales/pt/translation.json
- src/locales/pt_br/translation.json
- src/utils/dictionaries/liquidity-pool-dictionary.ts
- src/utils/graphql/rsk/generated.tsx
- src/utils/graphql/rsk/operations/getLiquidityMiningAllocationPoints.graphql
- yarn.lock
Milestone: https://github.com/DistributedCollective/Sovryn-frontend/milestone/10?closed=1
Release story: https://sovryn.atlassian.net/browse/SOV-2370
> SOV-2370: 2023-05-23 Radiance release preparation

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-2243
> SOV-2243: restore Mynt link in Header menu

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/utils/classifiers.ts
Reverts DistributedCollective/Sovryn-frontend#2524
> Revert "SOV-2243: restore Mynt link in Header menu"

- src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
Hotfix for https://sovryn.atlassian.net/browse/SOV-2301
> Lower max processable checkpoints

- src/app/pages/RewardPage/hooks/useGetFeesEarnedClaimAmount.ts
- src/app/pages/RewardPage/hooks/useGetNextPositiveCheckpoint.ts
Hotfix for https://sovryn.atlassian.net/browse/SOV-2301
> Fix checkpoints calculations

- src/app/components/UserAssets/components/UserAssetsTableRow.tsx
- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-2375
> SOV-2375: add RUSDT and RDOC assets links

- src/app/pages/RewardPage/components/ClaimForms/FeesEarnedClaimRow/index.tsx
https://sovryn.atlassian.net/browse/SOV-2488
> SOV-2488: update maxCheckpoints for fee claiming

- src/utils/blockchain/contracts.testnet.ts
https://sovryn.atlassian.net/browse/SOV-2639
> SOV-2639: update RBTCWrapperProxy testnet address

- CONTRIBUTING.md
- README.md
- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-2671
> SOV-2671: update Discord link in footer

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
- src/locales/en/translation.json
- src/locales/pt_br/translation.json
https://sovryn.atlassian.net/browse/SOV-2532
> SOV-2532: add title to sovryn.app menu

- src/utils/blockchain/contracts.testnet.ts
https://sovryn.atlassian.net/browse/SOV-2710
> SOV-2710: change swap network address

- src/app/components/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
- src/app/pages/PerpetualPage/components/CompetitionPage/components/RegisterDialog/index.tsx
https://sovryn.atlassian.net/browse/SOV-2669
> SOV-2669: change notification signature text

- src/app/components/UserAssets/Vesting/types.ts
- src/app/components/UserAssets/Vesting/useListOfUserVestings.ts
- src/locales/en/translation.json
https://sovryn.atlassian.net/browse/SOV-2777
> SOV-2777: new team vesting type

- src/app/components/UserAssets/Vesting/VestingWithdrawForm.tsx
- src/app/containers/StakePage/components/VestingContract.tsx
- src/app/containers/StakePage/components/WithdrawVesting.tsx
https://sovryn.atlassian.net/browse/SOV-2807
> SOV-2807: fix outdated vesting fee tx estimates

- src/app/pages/LendingPage/components/LendingDialog/index.tsx
https://sovryn.atlassian.net/browse/SOV-2785
> SOV-2785: Fix max withdrawal logic in D1 Lend page

- src/utils/blockchain/contracts.ts
https://sovryn.atlassian.net/browse/SOV-2812
> SOV-2812: new FastBTC bridge address

- src/app/constants.ts
- src/utils/helpers.ts
https://sovryn.atlassian.net/browse/SOV-2809
> SOV-2809: update max rbtc checkpoints

- src/app/pages/FastBtcPage/components/Withdraw/AddressForm.tsx
https://sovryn.atlassian.net/browse/SOV-2934
> SOV-2934: validate fast-btc address

- src/app/hooks/staking/useGetUnlockedVesting.ts
https://sovryn.atlassian.net/browse/SOV-2957
> SOV-2957: 4 year vesting not respecting extendedDuration

- package.json
https://sovryn.atlassian.net/browse/SOV-2903
> SOV-2903: Add full Defiant wallet support

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/hooks/useGetFilteredDates.ts
- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/hooks/useGetVestingAddresses.ts
- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
- src/locales/en/translation.json
https://sovryn.atlassian.net/browse/SOV-3077
> SOV-3077: update claim button logic

- src/app/components/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
- src/utils/helpers.ts
- yarn.lock
https://sovryn.atlassian.net/browse/SOV-2787
> SOV-2787: access to notification service

- src/app/pages/RewardPage/components/FeesEarnedTab/useHandleClaimAll.ts
- src/app/pages/RewardPage/hooks/useGetFeesEarned.ts
https://sovryn.atlassian.net/browse/SOV-3289
> SOV-3289: claim itokens

- src/app/pages/RewardPage/components/FeesEarnedTab/index.tsx
- src/app/pages/RewardPage/hooks/useGetFeesEarned.ts
https://sovryn.atlassian.net/browse/SOV-3360
> SOV-3360: corrected dummy rbtc claiming

- src/utils/classifiers.ts
https://sovryn.atlassian.net/browse/SOV-3422
> SOV-3422: increase suggested gas limit for claiming rewards

- package.json
- yarn.lock
https://sovryn.atlassian.net/browse/SOV-3376
> SOV-3376: bump sovryn wallet connect version

- package.json
- yarn.lock
https://sovryn.atlassian.net/browse/SOV-3376
> SOV-3376: bump sovryn wallet connection package version

- src/app/pages/RewardPage/hooks/useGetLiquidSovClaimAmount.ts
Resolves https://sovryn.atlassian.net/browse/SOV-3727
> SOV-3727: Adjust staking rewards claim

- src/locales/fr/translation.json
> Update translation.json FR

- src/app/pages/MarginTradePage/components/AddToMarginDialog/index.tsx
- src/app/pages/MarginTradePage/components/ClosePositionDialog/index.tsx
- src/app/pages/MarginTradePage/components/ClosedPositionsTable/ClosedPositionRow.tsx
https://sovryn.atlassian.net/browse/SOV-3802
> SOV-3802: Fix mismatch in collateral on margin trade positions

- src/app/pages/RewardPage/components/ClaimForms/BaseClaimForm/index.tsx
https://sovryn.atlassian.net/browse/SOV-3959
> SOV-3959: TEMP patch to prevent future LM "dead vestings"

- public/index.html
https://sovryn.atlassian.net/browse/SOV-4240
> SOV-4240: update tiledesk version

- src/app/pages/FastBtcPage/constants.ts
Resolves [SOV-4497](https://sovryn.atlassian.net/browse/SOV-4497)
[SOV-4497]: https://sovryn.atlassian.net/browse/SOV-4497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SOV-4497: Fix FastBTC fee

- src/app/containers/PageContainer/components/DefaultHeaderComponent/DefaultHeaderComponent.tsx
https://sovryn.atlassian.net/browse/SOV-4812
> chore: add origins link

- src/app/pages/BridgeDepositPage/dictionaries/bridge-network-dictionary.ts
https://sovryn.atlassian.net/browse/SOV-4802
> chore: fix issue with eDLLR (change RPC)

- src/app/pages/MarginTradePage/components/TxFeeCalculator/index.tsx
- src/app/pages/SpotTradingPage/components/TradeDialog/index.tsx
Resolves https://sovryn.atlassian.net/browse/SOV-4870
> SOV-4870: Hide fee estimations

- src/app/pages/MarginTradePage/components/OpenPositionsTable/PositionRow.tsx
https://sovryn.atlassian.net/browse/SOV-4811
> SOV-4811: Enable margin button if current margin is zero
